version: '3.8'

services:
  web-app:
    build: .
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-net
    depends_on:
      - redis-db

  redis-db:
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  redis-data: